// Pixel art (16×16) for click tiers and producers, rendered to data-URI PNGs
// at runtime. Lives outside src/lib/ because rendering needs a canvas (DOM).
// Grid chars map to PALETTE; "." = transparent.
export const PALETTE: Record<string, string> = {
  K: "#3B2A1A", N: "#8B5E3C", n: "#6B4226", G: "#F4B942", g: "#C98A2B",
  Y: "#FFE08A", C: "#FBF4E4", O: "#E8762C", o: "#B5541C", R: "#C0392B",
  W: "#FFFFFF", E: "#3E8E5A", e: "#2A6B41", B: "#3A6EA5", b: "#27496D",
  S: "#9AA0A6", s: "#5F6368", p: "#7C5CBF",
};

export const GRIDS: Record<string, string[]> = {
  // ── click tiers ──
  "tier-0": [ // donation box + coin
    "......KGGK......",
    "......KGGK......",
    ".......KK.......",
    "..KKKKKKKKKKKK..",
    "..KnnnnKKnnnnK..",
    "..KKKKKKKKKKKK..",
    "..KNNNNNNNNNNK..",
    "..KNNNNNNNNNNK..",
    "..KNGGGGGGGGNK..",
    "..KNGYGGGGYGNK..",
    "..KNGGGGGGGGNK..",
    "..KNNNNNNNNNNK..",
    "..KNNNNNNNNNNK..",
    "..KnNNNNNNNNnK..",
    "..KKKKKKKKKKKK..",
    "................",
  ],
  "tier-1": [ // alms bowl + rice
    "................",
    "......WWWW......",
    ".....WWWWWW.....",
    "....WWWWWWWW....",
    "...KKKKKKKKKK...",
    "..KGGGGGGGGGGK..",
    "..KGYGGGGGGGGK..",
    "..KGYGGGGGGGgK..",
    "..KGGGGGGGGGgK..",
    "...KgGGGGGGgK...",
    "....KgGGGGgK....",
    ".....KKKKKK.....",
    "......KggK......",
    ".....KggggK.....",
    "....KKKKKKKK....",
    "................",
  ],
  "tier-2": [ // offering bucket
    ".....KKKKKK.....",
    "....K......K....",
    "...K........K...",
    "..KKKKKKKKKKKK..",
    "..KWWKRRKEEKWK..",
    "..KWWKRRKEEKWK..",
    "..KKKKKKKKKKKK..",
    "..KOOYYOOOOOOK..",
    "..KOOYYOOOOOOK..",
    "..KOOOYYOOOOOK..",
    "...KOOOOOOOOK...",
    "...KOOOOOOOOK...",
    "...KooOOOOooK...",
    "....KooooooK....",
    "....KKKKKKKK....",
    "................",
  ],
  "tier-3": [ // boundary-stone sphere + gold leaf
    "................",
    ".....KKKKKK.....",
    "....KSSSSSSK....",
    "...KSSWSSSSSK...",
    "..KSSssssssSSK..",
    "..KSsGGssssssK..",
    "..KSGGGGsssssK..",
    "..KSsGGssGGssK..",
    "..KSsssssGGssK..",
    "..KSssssssssSK..",
    "..KSSsssssssSK..",
    "...KSSssssssK...",
    "....KSSSSSSK....",
    ".....KKKKKK.....",
    "....KKKKKKKK....",
    "................",
  ],
  "tier-4": [ // phone with QR
    "....KKKKKKKK....",
    "....KWWWWWWK....",
    "....KWKKWKWK....",
    "....KWKKWWWK....",
    "....KWWWKKWK....",
    "....KWKWWKWK....",
    "....KWKKWWWK....",
    "....KWWWWKWK....",
    "....KWKWKKWK....",
    "....KWWWWWWK....",
    "....KKKKKKKK....",
    "....KssssssK....",
    "....KsKGGKsK....",
    "....KssssssK....",
    "....KKKKKKKK....",
    "......YY........",
  ],
  // ── producers ──
  "p0": [ // morning alms tray
    "................",
    "......Y.Y.......",
    ".....Y.Y.Y......",
    "................",
    "...KK......KK...",
    "..KWWK.RR.KEEK..",
    "..KWWKKRRKKEEK..",
    "..KWWKKRRKKEEK..",
    "...KKKKKKKKKK...",
    "..KNNNNNNNNNNK..",
    "...KnNNNNNNnK...",
    "....KKKKKKKK....",
    "................",
    "................",
    "................",
    "................",
  ],
  "p1": [ // smart donation kiosk
    "....KKKKKKKK....",
    "....KSSSSSSK....",
    "....KSKKKKSK....",
    "....KSKBBKSK....",
    "....KSKBBKSK....",
    "....KSKKKKSK....",
    "....KSSSSSSK....",
    "....KSGYGYSK....",
    "....KSYGYGSK....",
    "....KSSSSSSK....",
    "....KSKKKKSK....",
    "....KSSSSSSK....",
    "....KSSSSSSK....",
    "....KssssssK....",
    "....KKKKKKKK....",
    "...KKK....KKK...",
  ],
  "p2": [ // open cage + flying bird
    "................",
    "......K...K.....",
    ".....KBK.KBK....",
    "......KBKBK.....",
    ".....KBBBBBKO...",
    "......KBBBK.....",
    ".......KKK......",
    "............Y...",
    "..KKKKK....Y....",
    ".K.....K........",
    ".K.K.K.KK.......",
    ".K.K.K.K.K......",
    ".K.K.K.K..K.....",
    ".KKKKKKK........",
    "..KnnnnK........",
    "...KKKK.........",
  ],
  "p3": [ // free-food pot + steam
    ".....W....W.....",
    "....W....W......",
    ".....W....W.....",
    "....W....W......",
    "................",
    "..KK........KK..",
    "..KKKKKKKKKKKK..",
    "...KssssssssK...",
    "..KssssssssssK..",
    "..KsOOOOOOOOsK..",
    "..KssssssssssK..",
    "..KssssssssssK..",
    "..KsssssssssK...",
    "...KKKKKKKKK....",
    "....KK...KK.....",
    "................",
  ],
  "p4": [ // money tree
    "......KWWK......",
    ".....KWWWWK.....",
    "..KWWKWWWWKWWK..",
    ".KWWWWKWWKWWWWK.",
    "..KWWK.KK.KWWK..",
    "....K..KK..K....",
    ".......KK.......",
    ".....KKNNKK.....",
    ".......NN.......",
    ".......NN.......",
    "......KNNK......",
    "....KKKKKKKK....",
    "...KRRRRRRRRK...",
    "...KRRRRRRRRK...",
    "....KRRRRRRK....",
    "....KKKKKKKK....",
  ],
  "p5": [ // naga lamp post
    "......YYY.......",
    ".....YKKKY......",
    ".....KYYYK......",
    ".....KYYYK......",
    "..RR..KKK.......",
    ".KRRK..K........",
    ".KEWEK.K........",
    ".KEEEKKK........",
    "..KEEEEK........",
    "...KKEEK........",
    ".....KEK........",
    ".....KEK........",
    ".....KEK........",
    "....KEEEK.......",
    "...KEEEEEK......",
    "...KKKKKKK......",
  ],
  "p6": [ // online temple laptop
    "................",
    "................",
    "...KKKKKKKKKK...",
    "...KWWWWWWWWK...",
    "...KWKKWWKWWK...",
    "...KWKKWKKWWK...",
    "...KWWWKWWKWK...",
    "...KWKWWKKWWK...",
    "...KWWWWWWWWK...",
    "...KKKKKKKKKK...",
    "..KssssssssssK..",
    ".KssssssssssssK.",
    ".KKKKKKKKKKKKKK.",
    "................",
    "................",
    "................",
  ],
  "p7": [ // delivery box on wheel
    "................",
    "................",
    "...KKKKKKKK.....",
    "..KOOOOOOOOK....",
    "..KOKWWWWKOK....",
    "..KOKWWWWKOK....",
    "..KOOOOOOOOK....",
    "..KOOOOOOOOK.K..",
    "..KKKKKKKKKKKK..",
    "......KssK......",
    ".....KKKKKK.....",
    ".....Ks..sK.....",
    ".....Ks..sK.....",
    ".....KKKKKK.....",
    "................",
    "................",
  ],
  "p8": [ // mining rig + coin
    "......KGGK......",
    ".....KGYYGK.....",
    ".....KGYYGK.....",
    "......KGGK......",
    "................",
    "..KKKKKKKKKKKK..",
    "..KEKEKEKEKEKK..",
    "..KEKEKEKEKEKK..",
    "..KKKKKKKKKKKK..",
    "..KEKEKEKEKEKK..",
    "..KEKEKEKEKEKK..",
    "..KKKKKKKKKKKK..",
    "..KsssssssssKK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
  ],
  "p9": [ // merit satellite
    "....Y.....Y.....",
    ".....Y...Y......",
    "......Y.Y.......",
    "..KKK.....KKK...",
    "..KBBK...KBBK...",
    "..KBBKKKKKBBK...",
    "..KBBKSSSKBBK...",
    "..KBBKSGSKBBK...",
    "..KBBKSSSKBBK...",
    "..KBBKKKKKBBK...",
    "..KKK..K..KKK...",
    ".......K........",
    "......YYY.......",
    ".....Y.Y.Y......",
    "....Y..Y..Y.....",
    "................",
  ],
  "p10": [ // heavenly portal gate
    ".....KKKKKK.....",
    "....KGGGGGGK....",
    "...KGGKKKKGGK...",
    "..KGGKppppKGGK..",
    "..KGKppWWppKGK..",
    "..KGKpWWWWpKGK..",
    "..KGKpWCCWpKGK..",
    "..KGKpWCCWpKGK..",
    "..KGKpWWWWpKGK..",
    "..KGKppWWppKGK..",
    "..KGKppppppKGK..",
    "..KGKppppppKGK..",
    "..KGGKppppKGGK..",
    "..KGGGKKKKGGGK..",
    ".KKKKKKKKKKKKKK.",
    "................",
  ],
};

const cache = new Map<string, string>();

/** Render a grid to a 16×16 PNG data-URI (cached). "" when canvas unavailable. */
export function spriteURL(id: string): string {
  const hit = cache.get(id);
  if (hit !== undefined) return hit;
  const rows = GRIDS[id];
  if (!rows) return "";
  const canvas = document.createElement("canvas");
  canvas.width = 16;
  canvas.height = 16;
  const ctx = canvas.getContext("2d");
  if (!ctx) return "";
  rows.forEach((row, y) => {
    for (let x = 0; x < 16; x++) {
      const ch = row[x] ?? ".";
      if (ch === ".") continue;
      ctx.fillStyle = PALETTE[ch] ?? "#FF00FF";
      ctx.fillRect(x, y, 1, 1);
    }
  });
  const url = canvas.toDataURL("image/png");
  cache.set(id, url);
  return url;
}
